integer:
  name: integer
  type: integer
  generation:
    method: sequence
    start: 1
float:
  name: float
  type: float
  generation:
    method: random
    start: 0.0
    end: 100.0
    interval: 1.0
    decimal_places: 2
string:
  name: string
  type: string
  generation:
    method: sequence
boolean:
  name: boolean
  type: boolean
  generation:
    method: sequence
timestamp:
  name: timestamp
  type: timestamp
  generation:
    method: sequence
    start: "2020-01-01 00:00:00"
    end: "2024-12-31 23:59:59"
    interval: 60