default:
  type: postgres
  host: localhost
  port: 5432
  dbname: postgres
  user: postgres
  password: postgres

postgres:
  type: postgres
  host: localhost
  port: 5432
  dbname: postgres
  user: postgres
  password: postgres

mysql:
  type: mysql
  host: localhost
  port: 3306
  dbname: mysql
  user: root
  password: mysqlroot

rds:
  type: rds
  region: ap-northeast-1
  profile: default
  host: arn:aws:rds:ap-northeast-1:xxxxxxxxxxxx:cluster:database-1
  dbname: postgres
  secret_arn: arn:aws:secretsmanager:ap-northeast-1:xxxxxxxxxxxx:secret:rds-db-credentials/cluster-xxxxxxxxxxxxpostgres/xxxxxxxxxxxx
  bucket_name: redshift-load-bucket-001
  object_key: csv_load/data.csv
  iam_role: arn:aws:iam::xxxxxxxxxxxx:role/rds-csv-load-role

redshift_serverless:
  type: redshift_serverless
  region: ap-northeast-1
  profile: default
  host: redshift-workgroup
  dbname: dev
  bucket_name: redshift-load-bucket-001
  object_key: csv_load/data.csv
  iam_role: arn:aws:iam::xxxxxxxxxxxx:role/redshift-load-role

redshift:
  type: redshift
  region: ap-northeast-1
  profile: default
  host: redshift-cluster
  dbname: dev
  bucket_name: redshift-load-bucket-001
  object_key: csv_load/data.csv
  iam_role: arn:aws:iam::xxxxxxxxxxxx:role/redshift-load-role

dynamodb:
  type: dynamodb
  region: ap-northeast-1
  profile: default
  bucket_name: dynamodb-xxxxxxxxxxxx-load-bucket-001
  object_key: json_load/data.json
  source_table: products_source
