settings:
  data_generation:
    database:
      batch_size: 10000      # Batch insert size for the database
      commit_interval: 100   # Interval for committing transactions (in milliseconds)
    csv:
      delimiter: ','         # Delimiter character for the CSV
      include_headers: true # Whether to include headers in the CSV file
      batch_size: 100000     # Batch write size for the CSV file
    json:
      batch_size: 100000     # Batch write size for the JSON file
  logging:
    level: INFO              # Logging level: DEBUG, INFO, WARNING, ERROR
